[workspace]
resolver = "2"

members = [
    "ui",
    "usecase",
    "repository",
    "domain_handler",
    "domain",
    "util", "repository_handler",
]

[workspace.dependencies]
anyhow = "1.0.95"
thiserror = "2.0.11"