[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.132"
serde = {version = "1.0.214", features = ["derive"]}
reqwest = "0.11.14"
anyhow = { workspace = true }
thiserror = { workspace = true }